### ISSUE TITLE
There was an error uploading your package. Please try again or contact technical support.

### ISSUE THREAD

**Issue by srirayavarapu** [rokudev/docs#6]

**Comment by srirayavarapu** [comment]
Hello can some one help on this

**Comment by jr-roku** [comment]
Hi. I think it is likely that for a large package upload, even though you saw an error message, the package was uploaded. You can refresh your web browser and check the Preview and Publish page to check the version number updated properly and the downloadable package is the correct one. Alternatively, test using the Unpublished Access Code. 

We are working on a fix to the error message.

**Comment by fli-ssullivan** [comment]
I'm having the same issue with a small (< 300k) package. Tried both Chrome & FF. The Preview and Publish page indicate that the file did not upload.

**Comment by jr-roku** [comment]
@fli-ssullivan ~ can you please contact me directly? jroberts AT roku.com TIA

**Comment by fli-ssullivan** [comment]
I'm no longer have any problems uploading packages with the portal. Thanks!

**Comment by jr-roku** [comment]
In general, if you have problems uploading your package, make sure you have 'packaged' the application first using the instructions here:- https://sdkdocs.roku.com/display/sdkdoc/Packaging+Your+Application

**Comment by EnTerr** [comment]
This was a real bug in the dev.portal, not PEBCAK - multiple complaints. 
Seems to been fixed since.
@srirayavarapu, can you please close the issue?

**Comment by jr-roku** [comment]
Well, there is still an outstanding issue that if your application is not packaged, dev.portal reports an unhelpful error message rather than letting you know it failed because it was unpackaged. We have a fix pending for that - but in the meantime I wanted to remind people to check they have packaged their channel if they see the general error message.

**Comment by joetesta** [comment]
Where I work we have designated people who submit the packages for us.  Our guy was trying unsuccessfully for four days before I finally sat with him to watch what was happening, and noticed he was uploading a zip instead of a package.  IMO rather than failing silently, the developer site should alert the developer when an invalid file type is uploaded.   thank you.  https://forums.roku.com/viewtopic.php?f=34&t=98618
